spring.application.name=tasks
server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.show-sql=true

# Отключаем CHECK constraints для разработки
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Добавь эту настройку:
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# JWT настройки
jwt.secret=TXlTdXBlclNlY3JldEtleUZvckpXVDIzNDU2Nzg5MDEyMzQ1Njc4OTA=
jwt.expiration=86400000
jwt.refresh-expiration=604800000